### ISSUE TITLE
devtools::document()

### ISSUE THREAD

**Issue by fveitz** [TransBioInfoLab/coMethDMR#1]
When running devtools::document()

devtools::document()
Updating coMethDMR documentation
Loading coMethDMR
Error: Dependency package(s) 'BiocParallel','bumphunter','GenomicRanges','IRanges' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'BiocParallel' not available.
2: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'bumphunter' not available.
3: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'GenomicRanges' not available.
4: In (function (dep_name, dep_ver = "*")  :
  Dependency package 'IRanges' not available.

**Comment by gabrielodom** [comment]
@fveitz, If you see an error like the following: `Error: Dependency package(s) 'BiocParallel','bumphunter','GenomicRanges','IRanges' not available.`, then that means you should install these four packages from Bioconductor. 

First, install the [`BiocManager`](https://cran.r-project.org/web/packages/BiocManager/index.html) package from CRAN as usual (via `install.packages()`), then follow these steps to install the four missing packages: <https://www.bioconductor.org/install/>

**Comment by fveitz** [comment]
@gabrielodom, I have just done it, but it is still not working for  'bumphunter' package.
devtools::document()
Updating coMethDMR documentation
Loading coMethDMR
Error: Dependency package(s) 'bumphunter' not available.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In (function (dep_name, dep_ver = "*")  :
  Dependency package 'bumphunter' not available.
> 
==> devtools::check()

Updating coMethDMR documentation
Loading coMethDMR
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'bumphunter' not available.
Error: Dependency package(s) 'bumphunter' not available.
Backtrace:
    x
 1. \-devtools::check(, check_dir = dirname(getwd()))
 2.   \-devtools::document(pkg, quiet = quiet)
 3.     +-withr::with_envvar(...)
 4.     | \-base::force(code)
 5.     \-roxygen2::roxygenise(pkg$path, roclets, load_code = load_code)
 6.       \-roxygen2:::load_code(base_path)
 7.         \-pkgload::load_all(path, helpers = FALSE, attach_testthat = FALSE)
 8.           \-pkgload:::load_imports(path)
 9.             \-pkgload:::abort_for_missing_packages(res, imports$package)
Execution halted

Exited with status 1.

**Comment by fveitz** [comment]
@gabrielodom, I have just installed bumphunter, but I am stuck on dvtools::document() and dvtools::check() 
**BiocManager::install('bumphunter')**

Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'bumphunter'
trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/bumphunter_1.32.0.zip'
Content type 'application/zip' length 4699602 bytes (4.5 MB)
downloaded 4.5 MB

package ‘bumphunter’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\VAIO-PC\AppData\Local\Temp\RtmpEP3kgb\downloaded_packages
Old packages: 'cachem', 'data.table', 'dplyr', 'htmltools', 'kableExtra', 'MASS', 'Matrix',
  'mgcv', 'nlme', 'Rcpp', 'rtracklayer', 'SparseM', 'svglite', 'testthat', 'tibble', 'xfun'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
             binary source needs_compilation
cachem        1.0.3  1.0.4              TRUE
data.table   1.13.6 1.14.0              TRUE
kableExtra    1.3.1  1.3.4             FALSE
Matrix       1.2-18  1.3-2              TRUE
mgcv         1.8-33 1.8-34              TRUE
rtracklayer  1.49.5 1.50.0              TRUE
SparseM        1.78   1.81              TRUE
svglite     1.2.3.2  2.0.0              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/cachem_1.0.3.zip'
Content type 'application/zip' length 71442 bytes (69 KB)
downloaded 69 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/data.table_1.13.6.zip'
Content type 'application/zip' length 2599423 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/dplyr_1.0.4.zip'
Content type 'application/zip' length 1329695 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/htmltools_0.5.1.1.zip'
Content type 'application/zip' length 243817 bytes (238 KB)
downloaded 238 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/MASS_7.3-53.1.zip'
Content type 'application/zip' length 1187711 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Matrix_1.2-18.zip'
Content type 'application/zip' length 4506373 bytes (4.3 MB)
downloaded 4.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/mgcv_1.8-33.zip'
Content type 'application/zip' length 3335464 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/nlme_3.1-152.zip'
Content type 'application/zip' length 2374486 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Rcpp_1.0.6.zip'
Content type 'application/zip' length 3253235 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/rtracklayer_1.49.5.zip'
Content type 'application/zip' length 2929936 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/SparseM_1.78.zip'
Content type 'application/zip' length 1065447 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/svglite_1.2.3.2.zip'
Content type 'application/zip' length 851549 bytes (831 KB)
downloaded 831 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/testthat_3.0.2.zip'
Content type 'application/zip' length 2496093 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/tibble_3.0.6.zip'
Content type 'application/zip' length 836444 bytes (816 KB)
downloaded 816 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/xfun_0.21.zip'
Content type 'application/zip' length 319389 bytes (311 KB)
downloaded 311 KB

package ‘cachem’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘htmltools’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘htmltools’
Warning: restored ‘htmltools’
package ‘MASS’ successfully unpacked and MD5 sums checked
package ‘Matrix’ successfully unpacked and MD5 sums checked
package ‘mgcv’ successfully unpacked and MD5 sums checked
package ‘nlme’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘rtracklayer’ successfully unpacked and MD5 sums checked
package ‘SparseM’ successfully unpacked and MD5 sums checked
package ‘svglite’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘xfun’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘xfun’
Warning: restored ‘xfun’

The downloaded binary packages are in
	C:\Users\VAIO-PC\AppData\Local\Temp\RtmpEP3kgb\downloaded_packages
installing the source package ‘kableExtra’

trying URL 'https://cran.rstudio.com/src/contrib/kableExtra_1.3.4.tar.gz'
Content type 'application/x-gzip' length 1646490 bytes (1.6 MB)
downloaded 1.6 MB

* installing *source* package 'kableExtra' ...
** package 'kableExtra' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'gdtools'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'kableExtra'
* removing 'C:/Program Files/R/R-4.0.2/library/kableExtra'
* restoring previous 'C:/Program Files/R/R-4.0.2/library/kableExtra'

The downloaded source packages are in
	‘C:\Users\VAIO-PC\AppData\Local\Temp\RtmpEP3kgb\downloaded_packages’
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.0.2\library\00LOCK\htmltools\libs\x64\htmltools.dll to C:\Program Files\R\R-4.0.2\library\htmltools\libs\x64\htmltools.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.0.2\library\00LOCK\xfun\libs\x64\xfun.dll to C:\Program Files\R\R-4.0.2\library\xfun\libs\x64\xfun.dll: Permission denied
3: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘kableExtra’ had non-zero exit status


**> devtools::document()**

Updating coMethDMR documentation
Loading coMethDMR
Registered S3 methods overwritten by 'car':
  method                          from
  influence.merMod                lme4
  cooks.distance.influence.merMod lme4
  dfbeta.influence.merMod         lme4
  dfbetas.influence.merMod        lme4
Writing NAMESPACE
Error: 'enhancer.probes' is not an exported object from 'namespace:coMethDMR'
In addition: Warning messages:
1: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘IlluminaHumanMethylation450kanno.ilmn12.hg19’
2: In loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called ‘IlluminaHumanMethylationEPICanno.ilm10b2.hg19’

**==> devtools::check()**

Updating coMethDMR documentation
Loading coMethDMR
Warning in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'IlluminaHumanMethylation450kanno.ilmn12.hg19'
Warning in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  there is no package called 'IlluminaHumanMethylationEPICanno.ilm10b2.hg19'
Registered S3 methods overwritten by 'car':
  method                          from
  influence.merMod                lme4
  cooks.distance.influence.merMod lme4
  dfbeta.influence.merMod         lme4
  dfbetas.influence.merMod        lme4
Error: 'enhancer.probes' is not an exported object from 'namespace:coMethDMR'
Execution halted

Exited with status 1.

**Comment by gabrielodom** [comment]
Let's move this discussion to slack.

**Comment by fveitz** [comment]
Ok, Gabriel.
