### ISSUE TITLE
A question about the EPIC_10b4_Gene_3_200.rds and EPIC_10b4_InterGene_3_200.rds files

### ISSUE THREAD

**Issue by QianhuiWan** [TransBioInfoLab/coMethDMR#26]
Hello Gabriel, I couldn't find the code for generating the EPIC_10b4_Gene_3_200.rds and EPIC_10b4_InterGene_3_200.rds files. Are there any criteria for defining gene and intergenic methylation regions? Thanks!

Best regards
Qianhui

**Comment by lxw391** [comment]
Hi Qianhui - these clusters were created using the WriteClosebyAllRegions() function in the package. I believe genic regions are those probes with gene names in the Illumina manifest, intergenic regions are those probes without gene names in UCSC_RefGene_Name
-Lily

**Comment by QianhuiWan** [comment]
> Hi Qianhui - these clusters were created using the WriteClosebyAllRegions() function in the package. I believe genic regions are those probes with gene names in the Illumina manifest, intergenic regions are those probes without gene names in UCSC_RefGene_Name -Lily

**Comment by QianhuiWan** [comment]
> Hi Qianhui - these clusters were created using the WriteClosebyAllRegions() function in the package. I believe genic regions are those probes with gene names in the Illumina manifest, intergenic regions are those probes without gene names in UCSC_RefGene_Name -Lily

Hi Lily, thank you so much.
