### ISSUE TITLE
Probes kept when `rdrop == 0`

### ISSUE THREAD

**Issue by gabrielodom** [TransBioInfoLab/coMethDMR#7]
From @XiaoweiHu-Stat: for some probes, we calculate the rdrop statistic to be exactly equal to 0, but the `keep` indicator is still 1. This is an error.

We do not have access to the original data (due to data privacy concerns), so we cannot directly replicate this error. We will first try to create some synthetic data and force the rdrop values to be 0.

**Comment by gabrielodom** [comment]
We found the culprit: when there are missing values in the methylation data, the `cor()` function in `CreateRdrop()` returns all `NA`. Then, these `NA` values infect the `MarkComethylatedCpGs()` function, meaning that we end up checking if probe IDs are elements of a vector of missing values: 

```
dropCpGs_char <- CpGs_char[clusterRdrop_df$r_drop < rDropThresh_num]
keep = ifelse(CpGs_char %in% dropCpGs_char, 0, 1), ##(drop=0, keep=1)
```

I still don't know how the `r_drop` values are being changed from `NA` to 0, but this at least tells us why they aren't being removed.

**Comment by gabrielodom** [comment]
Possible solutions:
1. Add checks for missing values
2. Add an option to use the `use = "pairwise.complete.obs"` (or for the user to choose) option to `cor()` in `CreateRdrop()`.

**Comment by gabrielodom** [comment]
@XiaoweiHu-Stat, can you try again now?

**Comment by XiaoweiHu-Stat** [comment]
Hi Gabriel,

Thanks for the update. I will try it this week and let you know if there are any more questions.

Xiaowei
________________________________

**Comment by gabrielodom** [comment]
@fveitz, can you test the following two things:

**Comment by gabrielodom** [comment]
@fveitz, can you test the following two things:
1. Take the example data set in the package, and add a sample with all NA values. Try to replicate the error above (you may need to set `use = "everything"` in `CreateRdrop()` to replicate the error.
2. Same as above, but have half of the samples be NA, and the other half actual values (beta values can be drawn Uniform distribution)

**Comment by gabrielodom** [comment]
We have added preliminary data checking to the workflow (as shown in vignette 2) via the `MarkMissing()` function.
